import os

# Log
DATABASE_DIR = 'database'
if not os.path.exists(DATABASE_DIR):
    os.mkdir(DATABASE_DIR)

DATABASE_URL = f'sqlite:///./{DATABASE_DIR}/spiderfoot.db'

EVENT_DETAILS = [
    ['ROOT', 'Internal SpiderFoot Root event', 1, 'INTERNAL'],
    ['ACCOUNT_EXTERNAL_OWNED', 'Account on External Site', 0, 'ENTITY'],
    ['ACCOUNT_EXTERNAL_OWNED_COMPROMISED', 'Hacked Account on External Site', 0, 'DESCRIPTOR'],
    ['ACCOUNT_EXTERNAL_USER_SHARED_COMPROMISED', 'Hacked User Account on External Site', 0, 'DESCRIPTOR'],
    ['AFFILIATE_EMAILADDR', 'Affiliate - Email Address', 0, 'ENTITY'],
    ['AFFILIATE_INTERNET_NAME', 'Affiliate - Internet Name', 0, 'ENTITY'],
    ['AFFILIATE_INTERNET_NAME_HIJACKABLE', 'Affiliate - Internet Name Hijackable', 0, 'ENTITY'],
    ['AFFILIATE_INTERNET_NAME_UNRESOLVED', 'Affiliate - Internet Name - Unresolved', 0, 'ENTITY'],
    ['AFFILIATE_IPADDR', 'Affiliate - IP Address', 0, 'ENTITY'],
    ['AFFILIATE_IPV6_ADDRESS', 'Affiliate - IPv6 Address', 0, 'ENTITY'],
    ['AFFILIATE_WEB_CONTENT', 'Affiliate - Web Content', 1, 'DATA'],
    ['AFFILIATE_DOMAIN_NAME', 'Affiliate - Domain Name', 0, 'ENTITY'],
    ['AFFILIATE_DOMAIN_UNREGISTERED', 'Affiliate - Domain Name Unregistered', 0, 'ENTITY'],
    ['AFFILIATE_COMPANY_NAME', 'Affiliate - Company Name', 0, 'ENTITY'],
    ['AFFILIATE_DOMAIN_WHOIS', 'Affiliate - Domain Whois', 1, 'DATA'],
    ['AFFILIATE_DESCRIPTION_CATEGORY', 'Affiliate Description - Category', 0, 'DESCRIPTOR'],
    ['AFFILIATE_DESCRIPTION_ABSTRACT', 'Affiliate Description - Abstract', 0, 'DESCRIPTOR'],
    ['APPSTORE_ENTRY', 'App Store Entry', 0, 'ENTITY'],
    ['CLOUD_STORAGE_BUCKET', 'Cloud Storage Bucket', 0, 'ENTITY'],
    ['CLOUD_STORAGE_BUCKET_OPEN', 'Cloud Storage Bucket Open', 0, 'DESCRIPTOR'],
    ['COMPANY_NAME', 'Company Name', 0, 'ENTITY'],
    ['CREDIT_CARD_NUMBER', 'Credit Card Number', 0, 'ENTITY'],
    ['BASE64_DATA', 'Base64-encoded Data', 1, 'DATA'],
    ['BITCOIN_ADDRESS', 'Bitcoin Address', 0, 'ENTITY'],
    ['BITCOIN_BALANCE', 'Bitcoin Balance', 0, 'DESCRIPTOR'],
    ['BGP_AS_OWNER', 'BGP AS Ownership', 0, 'ENTITY'],
    ['BGP_AS_MEMBER', 'BGP AS Membership', 0, 'ENTITY'],
    ['BLACKLISTED_COHOST', 'Blacklisted Co-Hosted Site', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_INTERNET_NAME', 'Blacklisted Internet Name', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_AFFILIATE_INTERNET_NAME', 'Blacklisted Affiliate Internet Name', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_IPADDR', 'Blacklisted IP Address', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_AFFILIATE_IPADDR', 'Blacklisted Affiliate IP Address', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_SUBNET', 'Blacklisted IP on Same Subnet', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_NETBLOCK', 'Blacklisted IP on Owned Netblock', 0, 'DESCRIPTOR'],
    ['COUNTRY_NAME', 'Country Name', 0, 'ENTITY'],
    ['CO_HOSTED_SITE', 'Co-Hosted Site', 0, 'ENTITY'],
    ['CO_HOSTED_SITE_DOMAIN', 'Co-Hosted Site - Domain Name', 0, 'ENTITY'],
    ['CO_HOSTED_SITE_DOMAIN_WHOIS', 'Co-Hosted Site - Domain Whois', 1, 'DATA'],
    ['DARKNET_MENTION_URL', 'Darknet Mention URL', 0, 'DESCRIPTOR'],
    ['DARKNET_MENTION_CONTENT', 'Darknet Mention Web Content', 1, 'DATA'],
    ['DATE_HUMAN_DOB', 'Date of Birth', 0, 'ENTITY'],
    ['DEFACED_INTERNET_NAME', 'Defaced', 0, 'DESCRIPTOR'],
    ['DEFACED_IPADDR', 'Defaced IP Address', 0, 'DESCRIPTOR'],
    ['DEFACED_AFFILIATE_INTERNET_NAME', 'Defaced Affiliate', 0, 'DESCRIPTOR'],
    ['DEFACED_COHOST', 'Defaced Co-Hosted Site', 0, 'DESCRIPTOR'],
    ['DEFACED_AFFILIATE_IPADDR', 'Defaced Affiliate IP Address', 0, 'DESCRIPTOR'],
    ['DESCRIPTION_CATEGORY', 'Description - Category', 0, 'DESCRIPTOR'],
    ['DESCRIPTION_ABSTRACT', 'Description - Abstract', 0, 'DESCRIPTOR'],
    ['DEVICE_TYPE', 'Device Type', 0, 'DESCRIPTOR'],
    ['DNS_TEXT', 'DNS TXT Record', 0, 'DATA'],
    ['DNS_SRV', 'DNS SRV Record', 0, 'DATA'],
    ['DNS_SPF', 'DNS SPF Record', 0, 'DATA'],
    ['DOMAIN_NAME', 'Domain Name', 0, 'ENTITY'],
    ['DOMAIN_NAME_PARENT', 'Domain Name (Parent)', 0, 'ENTITY'],
    ['DOMAIN_REGISTRAR', 'Domain Registrar', 0, 'ENTITY'],
    ['DOMAIN_WHOIS', 'Domain Whois', 1, 'DATA'],
    ['EMAILADDR', 'Email Address', 0, 'ENTITY'],
    ['EMAILADDR_COMPROMISED', 'Hacked Email Address', 0, 'DESCRIPTOR'],
    ['EMAILADDR_DELIVERABLE', 'Deliverable Email Address', 0, 'DESCRIPTOR'],
    ['EMAILADDR_DISPOSABLE', 'Disposable Email Address', 0, 'DESCRIPTOR'],
    ['EMAILADDR_GENERIC', 'Email Address - Generic', 0, 'ENTITY'],
    ['EMAILADDR_UNDELIVERABLE', 'Undeliverable Email Address', 0, 'DESCRIPTOR'],
    ['ERROR_MESSAGE', 'Error Message', 0, 'DATA'],
    ['ETHEREUM_ADDRESS', 'Ethereum Address', 0, 'ENTITY'],
    ['ETHEREUM_BALANCE', 'Ethereum Balance', 0, 'DESCRIPTOR'],
    ['GEOINFO', 'Physical Location', 0, 'DESCRIPTOR'],
    ['HASH', 'Hash', 0, 'DATA'],
    ['HASH_COMPROMISED', 'Compromised Password Hash', 0, 'DATA'],
    ['HTTP_CODE', 'HTTP Status Code', 0, 'DATA'],
    ['HUMAN_NAME', 'Human Name', 0, 'ENTITY'],
    ['IBAN_NUMBER', 'IBAN Number', 0, 'ENTITY'],
    ['INTERESTING_FILE', 'Interesting File', 0, 'DESCRIPTOR'],
    ['INTERESTING_FILE_HISTORIC', 'Historic Interesting File', 0, 'DESCRIPTOR'],
    ['JUNK_FILE', 'Junk File', 0, 'DESCRIPTOR'],
    ['INTERNAL_IP_ADDRESS', 'IP Address - Internal Network', 0, 'ENTITY'],
    ['INTERNET_NAME', 'Internet Name', 0, 'ENTITY'],
    ['INTERNET_NAME_UNRESOLVED', 'Internet Name - Unresolved', 0, 'ENTITY'],
    ['IP_ADDRESS', 'IP Address', 0, 'ENTITY'],
    ['IPV6_ADDRESS', 'IPv6 Address', 0, 'ENTITY'],
    ['LEI', 'Legal Entity Identifier', 0, 'ENTITY'],
    ['JOB_TITLE', 'Job Title', 0, 'DESCRIPTOR'],
    ['LINKED_URL_INTERNAL', 'Linked URL - Internal', 0, 'SUBENTITY'],
    ['LINKED_URL_EXTERNAL', 'Linked URL - External', 0, 'SUBENTITY'],
    ['MALICIOUS_ASN', 'Malicious AS', 0, 'DESCRIPTOR'],
    ['MALICIOUS_BITCOIN_ADDRESS', 'Malicious Bitcoin Address', 0, 'DESCRIPTOR'],
    ['MALICIOUS_IPADDR', 'Malicious IP Address', 0, 'DESCRIPTOR'],
    ['MALICIOUS_COHOST', 'Malicious Co-Hosted Site', 0, 'DESCRIPTOR'],
    ['MALICIOUS_EMAILADDR', 'Malicious E-mail Address', 0, 'DESCRIPTOR'],
    ['MALICIOUS_INTERNET_NAME', 'Malicious Internet Name', 0, 'DESCRIPTOR'],
    ['MALICIOUS_AFFILIATE_INTERNET_NAME', 'Malicious Affiliate', 0, 'DESCRIPTOR'],
    ['MALICIOUS_AFFILIATE_IPADDR', 'Malicious Affiliate IP Address', 0, 'DESCRIPTOR'],
    ['MALICIOUS_NETBLOCK', 'Malicious IP on Owned Netblock', 0, 'DESCRIPTOR'],
    ['MALICIOUS_PHONE_NUMBER', 'Malicious Phone Number', 0, 'DESCRIPTOR'],
    ['MALICIOUS_SUBNET', 'Malicious IP on Same Subnet', 0, 'DESCRIPTOR'],
    ['NETBLOCK_OWNER', 'Netblock Ownership', 0, 'ENTITY'],
    ['NETBLOCKV6_OWNER', 'Netblock IPv6 Ownership', 0, 'ENTITY'],
    ['NETBLOCK_MEMBER', 'Netblock Membership', 0, 'ENTITY'],
    ['NETBLOCKV6_MEMBER', 'Netblock IPv6 Membership', 0, 'ENTITY'],
    ['NETBLOCK_WHOIS', 'Netblock Whois', 1, 'DATA'],
    ['OPERATING_SYSTEM', 'Operating System', 0, 'DESCRIPTOR'],
    ['LEAKSITE_URL', 'Leak Site URL', 0, 'ENTITY'],
    ['LEAKSITE_CONTENT', 'Leak Site Content', 1, 'DATA'],
    ['PASSWORD_COMPROMISED', 'Compromised Password', 0, 'DATA'],
    ['PHONE_NUMBER', 'Phone Number', 0, 'ENTITY'],
    ['PHONE_NUMBER_COMPROMISED', 'Phone Number Compromised', 0, 'DESCRIPTOR'],
    ['PHONE_NUMBER_TYPE', 'Phone Number Type', 0, 'DESCRIPTOR'],
    ['PHYSICAL_ADDRESS', 'Physical Address', 0, 'ENTITY'],
    ['PHYSICAL_COORDINATES', 'Physical Coordinates', 0, 'ENTITY'],
    ['PGP_KEY', 'PGP Public Key', 0, 'DATA'],
    ['PROXY_HOST', 'Proxy Host', 0, 'DESCRIPTOR'],
    ['PROVIDER_DNS', 'Name Server (DNS ''NS'' Records)', 0, 'ENTITY'],
    ['PROVIDER_JAVASCRIPT', 'Externally Hosted Javascript', 0, 'ENTITY'],
    ['PROVIDER_MAIL', 'Email Gateway (DNS ''MX'' Records)', 0, 'ENTITY'],
    ['PROVIDER_HOSTING', 'Hosting Provider', 0, 'ENTITY'],
    ['PROVIDER_TELCO', 'Telecommunications Provider', 0, 'ENTITY'],
    ['PUBLIC_CODE_REPO', 'Public Code Repository', 0, 'ENTITY'],
    ['RAW_RIR_DATA', 'Raw Data from RIRs/APIs', 1, 'DATA'],
    ['RAW_DNS_RECORDS', 'Raw DNS Records', 1, 'DATA'],
    ['RAW_FILE_META_DATA', 'Raw File Meta Data', 1, 'DATA'],
    ['SEARCH_ENGINE_WEB_CONTENT', 'Search Engine Web Content', 1, 'DATA'],
    ['SOCIAL_MEDIA', 'Social Media Presence', 0, 'ENTITY'],
    ['SIMILAR_ACCOUNT_EXTERNAL', 'Similar Account on External Site', 0, 'ENTITY'],
    ['SIMILARDOMAIN', 'Similar Domain', 0, 'ENTITY'],
    ['SIMILARDOMAIN_WHOIS', 'Similar Domain - Whois', 1, 'DATA'],
    ['SOFTWARE_USED', 'Software Used', 0, 'SUBENTITY'],
    ['SSL_CERTIFICATE_RAW', 'SSL Certificate - Raw Data', 1, 'DATA'],
    ['SSL_CERTIFICATE_ISSUED', 'SSL Certificate - Issued to', 0, 'ENTITY'],
    ['SSL_CERTIFICATE_ISSUER', 'SSL Certificate - Issued by', 0, 'ENTITY'],
    ['SSL_CERTIFICATE_MISMATCH', 'SSL Certificate Host Mismatch', 0, 'DESCRIPTOR'],
    ['SSL_CERTIFICATE_EXPIRED', 'SSL Certificate Expired', 0, 'DESCRIPTOR'],
    ['SSL_CERTIFICATE_EXPIRING', 'SSL Certificate Expiring', 0, 'DESCRIPTOR'],
    ['TARGET_WEB_CONTENT', 'Web Content', 1, 'DATA'],
    ['TARGET_WEB_CONTENT_TYPE', 'Web Content Type', 0, 'DESCRIPTOR'],
    ['TARGET_WEB_COOKIE', 'Cookies', 0, 'DATA'],
    ['TCP_PORT_OPEN', 'Open TCP Port', 0, 'SUBENTITY'],
    ['TCP_PORT_OPEN_BANNER', 'Open TCP Port Banner', 0, 'DATA'],
    ['TOR_EXIT_NODE', 'TOR Exit Node', 0, 'DESCRIPTOR'],
    ['UDP_PORT_OPEN', 'Open UDP Port', 0, 'SUBENTITY'],
    ['UDP_PORT_OPEN_INFO', 'Open UDP Port Information', 0, 'DATA'],
    ['URL_ADBLOCKED_EXTERNAL', 'URL (AdBlocked External)', 0, 'DESCRIPTOR'],
    ['URL_ADBLOCKED_INTERNAL', 'URL (AdBlocked Internal)', 0, 'DESCRIPTOR'],
    ['URL_FORM', 'URL (Form)', 0, 'DESCRIPTOR'],
    ['URL_FLASH', 'URL (Uses Flash)', 0, 'DESCRIPTOR'],
    ['URL_JAVASCRIPT', 'URL (Uses Javascript)', 0, 'DESCRIPTOR'],
    ['URL_WEB_FRAMEWORK', 'URL (Uses a Web Framework)', 0, 'DESCRIPTOR'],
    ['URL_JAVA_APPLET', 'URL (Uses Java Applet)', 0, 'DESCRIPTOR'],
    ['URL_STATIC', 'URL (Purely Static)', 0, 'DESCRIPTOR'],
    ['URL_PASSWORD', 'URL (Accepts Passwords)', 0, 'DESCRIPTOR'],
    ['URL_UPLOAD', 'URL (Accepts Uploads)', 0, 'DESCRIPTOR'],
    ['URL_FORM_HISTORIC', 'Historic URL (Form)', 0, 'DESCRIPTOR'],
    ['URL_FLASH_HISTORIC', 'Historic URL (Uses Flash)', 0, 'DESCRIPTOR'],
    ['URL_JAVASCRIPT_HISTORIC', 'Historic URL (Uses Javascript)', 0, 'DESCRIPTOR'],
    ['URL_WEB_FRAMEWORK_HISTORIC', 'Historic URL (Uses a Web Framework)', 0, 'DESCRIPTOR'],
    ['URL_JAVA_APPLET_HISTORIC', 'Historic URL (Uses Java Applet)', 0, 'DESCRIPTOR'],
    ['URL_STATIC_HISTORIC', 'Historic URL (Purely Static)', 0, 'DESCRIPTOR'],
    ['URL_PASSWORD_HISTORIC', 'Historic URL (Accepts Passwords)', 0, 'DESCRIPTOR'],
    ['URL_UPLOAD_HISTORIC', 'Historic URL (Accepts Uploads)', 0, 'DESCRIPTOR'],
    ['USERNAME', 'Username', 0, 'ENTITY'],
    ['VPN_HOST', 'VPN Host', 0, 'DESCRIPTOR'],
    ['VULNERABILITY_DISCLOSURE', 'Vulnerability - Third Party Disclosure', 0, 'DESCRIPTOR'],
    ['VULNERABILITY_CVE_CRITICAL', 'Vulnerability - CVE Critical', 0, 'DESCRIPTOR'],
    ['VULNERABILITY_CVE_HIGH', 'Vulnerability - CVE High', 0, 'DESCRIPTOR'],
    ['VULNERABILITY_CVE_MEDIUM', 'Vulnerability - CVE Medium', 0, 'DESCRIPTOR'],
    ['VULNERABILITY_CVE_LOW', 'Vulnerability - CVE Low', 0, 'DESCRIPTOR'],
    ['VULNERABILITY_GENERAL', 'Vulnerability - General', 0, 'DESCRIPTOR'],
    ['WEB_ANALYTICS_ID', 'Web Analytics', 0, 'ENTITY'],
    ['WEBSERVER_BANNER', 'Web Server', 0, 'DATA'],
    ['WEBSERVER_HTTPHEADERS', 'HTTP Headers', 1, 'DATA'],
    ['WEBSERVER_STRANGEHEADER', 'Non-Standard HTTP Header', 0, 'DATA'],
    ['WEBSERVER_TECHNOLOGY', 'Web Technology', 0, 'DESCRIPTOR'],
    ['WIFI_ACCESS_POINT', 'WiFi Access Point Nearby', 0, 'ENTITY'],
    ['WIKIPEDIA_PAGE_EDIT', 'Wikipedia Page Edit', 0, 'DESCRIPTOR'],
]